WITH NO_MASTER_ITEM AS (
    SELECT
        ITEM_ID
    FROM
        ITEM_TREE
    WHERE
        ITEM_ID IN(SELECT PARENT_ITEM_ID FROM ITEM_TREE)
)

SELECT
    I.ITEM_ID,
    I.ITEM_NAME,
    I.RARITY
FROM 
    ITEM_INFO AS I
    LEFT OUTER JOIN NO_MASTER_ITEM AS N
    ON I.ITEM_ID = N.ITEM_ID
WHERE
    N.ITEM_ID IS NULL
ORDER BY
    I.ITEM_ID DESC