SELECT
    YEAR(S.SALES_DATE) AS YEAR,
    MONTH(S.SALES_DATE) AS MONTH,
    COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT U.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PURCHASED_RATIO
FROM
    USER_INFO AS U
    INNER JOIN ONLINE_SALE AS S
    ON U.USER_ID = S.USER_ID
    AND YEAR(U.JOINED) = 2021
GROUP BY
    YEAR(S.SALES_DATE),
    MONTH(S.SALES_DATE)
ORDER BY
    YEAR,
    MONTH