WITH RECURSIVE GENERATION AS(
    SELECT 
        ID,
        1 AS GEN
    FROM 
        ECOLI_DATA
    WHERE 
        PARENT_ID IS NULL

    UNION ALL

    SELECT 
        E.ID, 
        G.GEN+1 AS GEN
    FROM 
        ECOLI_DATA AS E
        INNER JOIN GENERATION AS G
        ON E.PARENT_ID = G.ID
)

SELECT 
    COUNT(*) AS `COUNT`,
    GEN AS GENERATION
FROM 
    GENERATION AS G
    LEFT JOIN ECOLI_DATA AS E
    ON G.ID = E.PARENT_ID
WHERE 
    E.ID IS NULL
GROUP BY 
    GENERATION
ORDER BY 
    GENERATION