WITH ORDER_MAY AS (
    SELECT *
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
)

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * SUM(O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS P
JOIN ORDER_MAY AS O
    ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY O.PRODUCT_ID
ORDER BY P.PRICE * SUM(O.AMOUNT) DESC, P.PRODUCT_ID
    