WITH PLAN AS (
    SELECT
        CAR_TYPE,
        CAST(REGEXP_REPLACE(DURATION_TYPE, '[^0-9]+', '') AS UNSIGNED) AS DURATION,
        CAST(REPLACE(DISCOUNT_RATE, '%', '') AS DECIMAL(5,2)) AS DISCOUNT_RATE
    FROM
        CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE
        CAR_TYPE = '트럭'
),
APPLIED_DISCOUNT AS (
    SELECT
        H.HISTORY_ID,
        C.DAILY_FEE,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS RENT_DAYS,
        (
            SELECT P.DISCOUNT_RATE
            FROM PLAN P
            WHERE RENT_DAYS >= P.DURATION
            ORDER BY P.DURATION DESC
            LIMIT 1
        ) AS DISCOUNT_RATE
    FROM
        CAR_RENTAL_COMPANY_CAR C
        JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
    WHERE
        C.CAR_TYPE = '트럭'
)

SELECT
    HISTORY_ID,
    FLOOR(DAILY_FEE * RENT_DAYS * (1 - IFNULL(DISCOUNT_RATE, 0) / 100)) AS FEE
FROM
    APPLIED_DISCOUNT
ORDER BY
    FEE DESC,
    HISTORY_ID DESC;