WITH HALF_SUM AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
    ORDER BY TOTAL_ORDER DESC
), JULY_SUM AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
    ORDER BY TOTAL_ORDER DESC
)

SELECT H.FLAVOR
FROM HALF_SUM H
INNER JOIN JULY_SUM J
    ON H.FLAVOR = J.FLAVOR
ORDER BY (H.TOTAL_ORDER + J.TOTAL_ORDER) DESC
LIMIT 3