WITH ITEM_PARENT_IDS AS (
    SELECT T.ITEM_ID
    FROM ITEM_INFO AS I
    INNER JOIN ITEM_TREE AS T
        ON I.ITEM_ID = T.PARENT_ITEM_ID
    WHERE I.RARITY = 'RARE'
)

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
    FROM ITEM_INFO AS I
    WHERE I.ITEM_ID IN (
        SELECT ITEM_ID FROM ITEM_PARENT_IDS
    )
    ORDER BY I.ITEM_ID DESC