WITH MAX_SIZE_YEAR AS (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_YEAR
    FROM
        ECOLI_DATA
    GROUP BY
        YEAR(DIFFERENTIATION_DATE)
)

SELECT
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    M.MAX_SIZE_OF_YEAR - E.SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM
    ECOLI_DATA AS E
    INNER JOIN MAX_SIZE_YEAR AS M
    ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY
    YEAR,
    YEAR_DEV